eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: payment-ms
  datasource:
    username: root
    password: sa
    url: jdbc:h2:mem:to_do_list_db
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

server:
  port: 0

